name: MLOps Chest Cancer Detection CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run Data Ingestion Pipeline
      run: |
        python src/pipelines/stage_01_data_ingestion.py  # Run your data ingestion pipeline

    - name: Prepare the Base Model
      run: |
        python src/pipelines/stage_02_prepare_base_model.py  # Prepare the base model pipeline

    - name: Train the Model
      run: |
        python src/pipelines/stage_03_model_trainer.py  # Run the model training pipeline

    - name: Evaluate the Model
      run: |
        python src/pipelines/stage_04_model_evaluation.py  # Evaluate the model after training

    - name: Start the Prediction App
      run: |
        nohup python app.py &  # Run the app in the background
        sleep 10  # Wait for the app to start (adjust if needed)

 
